trigger:
  branches:
    include:
    - main
    - azuredevops
    - feature/*
    - bug/*

# Pool build
pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: devops
    endpoint: Application
    type: github
    name: LocTaRND/azure-devops-template
    ref: azuredevops

variables:
  - group: demo_var
  - name: projectname
    value: projecttemplate-frontend
  - name: toolversion
    value: 16

stages:
  - template: templates/react/build.yml@devops