---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $projectName
  namespace: $deployEnv
spec:
  selector:
    matchLabels:
      app: $projectName
      role: frontend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: $replicaCount
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: $projectName
        role: frontend
    spec:
      containers:
        - name: $projectName
          image: "$containerRegistry/$crNameSpace/$projectName-rx-runtime:$VERSION"
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: $deployEnv
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 80
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: $projectName
  namespace: $deployEnv
  labels:
    app: $projectName
    role: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: $projectName
    role: frontend
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-$projectName
  namespace: $deployEnv
  annotations:
    kubernetes.io/ingress.class: nginx-$deployEnv
spec:
  tls:
    - hosts:
        - $frontendHost
      secretName: tls-origin-dev
  rules:
    - host: $frontendHost
      http:
        paths:
          - path: /
            backend:
              serviceName: $projectName
              servicePort: 80
