ARG BASEIMG=custom-sdk-source
ARG IMG_VERSION=lts
FROM $BASEIMG:$IMG_VERSION as react-sdk

FROM nginx:stable-alpine
#Copy the build folder of the react app
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=react-sdk /src/build /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]